
version: "3.9"
services:
  backend:
    build:
      context: ./backend
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    ports: ["8000:8000"]
  frontend:
    build:
      context: ./frontend
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
      - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
    ports: ["3000:3000"]
    command: sh -c "npm run build && npm start"
    depends_on: [backend]
